[package]
name = "rice-bin"
version = "0.1.0"
authors = ["Stuart Reilly <stu@reilly-family.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.28"
pretty_env_logger = { version = "0.4.0", optional = true }
syslog = { version = "5.0.0", optional = true }
rice = { path = "../lib" }
log = "0.4.8"
shuteye = "0.3.3"
signal-hook = "0.1.15"

[features]
default = ["stderr"]
stderr = ["pretty_env_logger"]

[package.metadata.feature_groups]
log = ["stderr", "syslog"]

[build-dependencies]
cfg_feature_groups = "0.1.1"
